# Use an official Python runtime as a parent image
FROM python:3.10-slim
ADD "https://github.com/zcxw-code/docker-list-containers.git" skipcache

# Set the working directory in the container
WORKDIR /app

# Install git and clone the repository
RUN apt-get update && apt-get install -y git 

RUN git clone https://github.com/zcxw-code/docker-list-containers.git /app

# Change working directory to the cloned repository
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir fastapi uvicorn docker requests

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run uvicorn server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

